name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.305'

      - name: Restore dependencies
        run: dotnet restore EnsekTestAutomation sln
        working-directory: EnsekTestAutomation

      - name: Build solution
        run: dotnet build EnsekTestAutomation.sln --no-restore --configuration Release
        working-directory: EnsekTestAutomation

      - name: Run tests
        run: dotnet test EnsekTestAutomation.sln --logger "trx" --results-directory ./TestResults --no-build --verbosity normal --configuration Release
        working-directory: EnsekTestAutomation

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx
        
#      - name: Publish Test Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-results
#          path: '**/TestResults/**/*.trx'

#      - name: Install ReportGenerator
#        run: dotnet tool install -g dotnet-reportgenerator-globaltool

#      - name: Generate Test Report
#        run: reportgenerator -reports:EnsekTestAutomation/TestResults/**/*.trx -targetdir:TestReport -reporttypes:Html

#      - name: Upload HTML Test Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: html-test-report
#          path: TestReport
