name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.305'

      - name: Restore dependencies
        run: dotnet restore EnsekTestAutomation sln
        working-directory: ensek-tech-test/rest-api-testing/EnsekTestAutomation

      - name: Build solution
        run: dotnet build EnsekTestAutomation.sln --no-restore --configuration Release
        working-directory: ensek-tech-test/rest-api-testing/EnsekTestAutomation

      - name: Run tests
        run: dotnet test EnsekTestAutomation.sln --logger "trx" --results-directory ./TestResults --no-build --verbosity normal --configuration Release
        working-directory: ensek-tech-test/rest-api-testing/EnsekTestAutomation

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx
        
